name: xen_emojify
description: "xen_emojify is a versatile Flutter package designed to enhance user interaction by providing a rich and engaging way to display Facebook-like reactions within your app."
version: 1.0.0
homepage: https://github.com/xenSlayer/xen_emojify

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.3"

dependencies:
  flutter:
    sdk: flutter
  lottie: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
