name: Deploy example app to github pages

on:
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  web-deploy:
    name: xen_emojify web example app
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
      - uses: bluefireteam/flutter-gh-pages@v7
        with:
          workingDir: example
          baseHref: /xen_emojify/
